function readParams(){M_val=parseFloat(document.getElementById('sliderM').value);A_val=parseFloat(document.getElementById('sliderBeta').value);r0_val=parseFloat(document.getElementById('sliderMu').value);a0_val=parseFloat(document.getElementById('sliderA0').value);eosModel=document.getElementById('eosSelect').value;speedMultiplier=parseFloat(document.getElementById('sliderSpeed').value);autoStop=document.getElementById('chkAutoStop').checked;switch(eosModel){case'barotropic':eosParams.omega=parseFloat(document.getElementById('sliderOmega')?.value||-0.58);break;case'phantom':eosParams.Ap=parseFloat(document.getElementById('sliderAp')?.value||0.5);eosParams.alpha_p=parseFloat(document.getElementById('sliderAlphaP')?.value||1);break;case'chaplygin':eosParams.Ac=parseFloat(document.getElementById('sliderAc')?.value||2);eosParams.alpha_c=parseFloat(document.getElementById('sliderAlphaC')?.value||1);break;case'cosmicChap':eosParams.Agc=parseFloat(document.getElementById('sliderAgc')?.value||2);eosParams.n_gc=parseFloat(document.getElementById('sliderNgc')?.value||3);break;case'modCosmicChap':eosParams.Amcc=parseFloat(document.getElementById('sliderAmcc')?.value||2);eosParams.m_mcc=parseFloat(document.getElementById('sliderMmcc')?.value||3);break;}document.getElementById('valM').textContent=M_val.toFixed(2);document.getElementById('valBeta').textContent=A_val.toFixed(2);document.getElementById('valMu').textContent=r0_val.toFixed(2);document.getElementById('valA0').textContent=a0_val.toFixed(2);document.getElementById('valSpeed').textContent=speedMultiplier.toFixed(1)+'\u00d7';}

function updateEosParamsUI(){const container=document.getElementById('eosParams');let html='';switch(eosModel){case'barotropic':html+='<div class="slider-row"><label>&omega; <span class="val" id="valOmega">'+eosParams.omega.toFixed(2)+'</span></label><input type="range" id="sliderOmega" min="-1.5" max="0" step="0.01" value="'+eosParams.omega+'"></div>';break;case'phantom':html+='<div class="slider-row"><label>A<sub>p</sub> <span class="val" id="valAp">'+eosParams.Ap.toFixed(2)+'</span></label><input type="range" id="sliderAp" min="0" max="5" step="0.1" value="'+eosParams.Ap+'"></div><div class="slider-row"><label>&alpha;<sub>p</sub> <span class="val" id="valAlphaP">'+eosParams.alpha_p.toFixed(2)+'</span></label><input type="range" id="sliderAlphaP" min="0" max="3" step="0.1" value="'+eosParams.alpha_p+'"></div>';break;case'chaplygin':html+='<div class="slider-row"><label>A<sub>c</sub> <span class="val" id="valAc">'+eosParams.Ac.toFixed(2)+'</span></label><input type="range" id="sliderAc" min="0.1" max="10" step="0.1" value="'+eosParams.Ac+'"></div><div class="slider-row"><label>&alpha;<sub>c</sub> <span class="val" id="valAlphaC">'+eosParams.alpha_c.toFixed(2)+'</span></label><input type="range" id="sliderAlphaC" min="0.1" max="3" step="0.1" value="'+eosParams.alpha_c+'"></div>';break;case'cosmicChap':html+='<div class="slider-row"><label>A<sub>gc</sub> <span class="val" id="valAgc">'+eosParams.Agc.toFixed(2)+'</span></label><input type="range" id="sliderAgc" min="0.1" max="10" step="0.1" value="'+eosParams.Agc+'"></div><div class="slider-row"><label>n<sub>gc</sub> <span class="val" id="valNgc">'+eosParams.n_gc.toFixed(2)+'</span></label><input type="range" id="sliderNgc" min="1" max="5" step="0.1" value="'+eosParams.n_gc+'"></div>';break;case'modCosmicChap':html+='<div class="slider-row"><label>A<sub>mcc</sub> <span class="val" id="valAmcc">'+eosParams.Amcc.toFixed(2)+'</span></label><input type="range" id="sliderAmcc" min="0.1" max="10" step="0.1" value="'+eosParams.Amcc+'"></div><div class="slider-row"><label>m<sub>mcc</sub> <span class="val" id="valMmcc">'+eosParams.m_mcc.toFixed(2)+'</span></label><input type="range" id="sliderMmcc" min="1" max="5" step="0.1" value="'+eosParams.m_mcc+'"></div>';break;}container.innerHTML=html;container.querySelectorAll('input[type="range"]').forEach(sl=>{sl.addEventListener('input',()=>{readParams();if(simRunning)resetSim();});});}

function updateHorizonInfo(){const[rPlus]=findHorizons(M_val,A_val,r0_val);const infoEl=document.getElementById('horizonInfo');const warnEl=document.getElementById('horizonWarn');const a0Slider=document.getElementById('sliderA0');if(rPlus!==null){infoEl.textContent='Horizon r\u208a: '+rPlus.toFixed(3);a0Slider.min=(rPlus+0.05).toFixed(3);a0Slider.max=Math.max(rPlus*4,5).toFixed(3);if(a0_val<=rPlus+0.01){warnEl.style.display='block';a0Slider.value=rPlus+0.1;a0_val=parseFloat(a0Slider.value);document.getElementById('valA0').textContent=a0_val.toFixed(2);}else warnEl.style.display='none';}else{infoEl.textContent='No horizon found (regular geometry)';a0Slider.min='0.3';a0Slider.max='5.0';warnEl.style.display='none';}}

function calibrateAtA0(){const f_a0=lapseF(a0_val,M_val,A_val,r0_val);if(f_a0<=0)return;switch(eosModel){case'barotropic':eosParams.omega=calibrateOmega(a0_val,M_val,A_val,r0_val);break;case'phantom':eosParams.Ap=calibratePhantomParams(a0_val,M_val,A_val,r0_val);break;case'chaplygin':eosParams.Ac=calibrateChaplyginParams(a0_val,M_val,A_val,r0_val);break;case'cosmicChap':eosParams.Agc=calibrateCosmicChap(a0_val,M_val,A_val,r0_val);break;case'modCosmicChap':eosParams.Amcc=calibrateModCosmicChap(a0_val,M_val,A_val,r0_val);break;}calibrated=true;updateEosParamsUI();resetSim();}

function initSim(){const f_a0=lapseF(a0_val,M_val,A_val,r0_val);if(f_a0<=0)return;let deltaAPct=parseFloat(document.getElementById('sliderDeltaA').value);if(document.getElementById('chkSmallPerturb').checked)deltaAPct=0.01;v_current=parseFloat(document.getElementById('sliderV0').value);tau=0;a_current=a0_val*(1+deltaAPct/100);timeHistory=[{tau:0,a:a_current,v:v_current}];phaseHistory=[{a:a_current,v:v_current}];calibrated=true;}

function resetSim(){simRunning=false;simPaused=false;readParams();initSim();}

let lastTime=0;

export { readParams, updateEosParamsUI, updateHorizonInfo, calibrateAtA0, initSim, resetSim };
